Improved spec file to latest standards and fixed changelog
Scribery/tlog pull request #337
Opened 2021-11-24 21:03 UTC by kees-closed

* Removed tmpfilesdir conditions, added systemd-rpm-macros as build
requirement
* Replacing short command options with the long notation, e.g. -m is
now --mode
* Removed compatibility macros, not needed anymore
* Cleaned up build dependencies
* Removed ldconfig commands from post and postun
* Bumped version to 12th release

2021-11-30 11:59 UTC, Conan-Kudo requested changes

2021-11-30 11:59 UTC, Conan-Kudo commented on tlog.spec
> +Source1:        %{name}-tmpfiles.conf
If it's in the source tree, you don't need it here.

2021-11-30 11:59 UTC, Conan-Kudo commented on tlog.spec
> -BuildRequires:  libtool
These are required when building from the source tree, as the autotools scripts are not committed in version control.

2021-11-30 11:59 UTC, Conan-Kudo commented on tlog.spec
> +BuildRequires:  systemd-rpm-macros
This will break it for RHEL 7, as `systemd-rpm-macros` doesn't exist there.

2021-11-30 11:59 UTC, Conan-Kudo commented on tlog.spec
> -/sbin/ldconfig
This is still needed for older distributions (RHEL 6/7) and other distributions (Debian/Ubuntu, SUSE, etc.).

2021-11-30 11:59 UTC, Conan-Kudo commented on tlog.spec
> -
This is still needed for older distributions (RHEL 6/7) and other distributions (Debian/Ubuntu, SUSE, etc.).

2021-11-30 11:59 UTC, Conan-Kudo commented on tlog.spec
> -%{!?make_build:%global make_build %{__make} %{?_smp_mflags}}
Removing this breaks the build for SLE 12 and RHEL 6.

2022-02-16 14:23 UTC, kees-closed commented
Thanks for the review @Conan-Kudo, all makes sense. Then I guess it's better to leave it as is. I'm still not a fan to include other distros such as Debian/Ubuntu in a spec file and support older systems that aren't even in the EPEL repos. But that's not up to me of course.

So the only thing that needs to get fixed is the changelog then. However, I do see F35 and F35 RPMs in the release directories. Does this mean there is a working RPM spec file already? If so, could you please update the one in the main branch? I wanted to complete this pull request. But if this is already done, then there is no need to spend time on it.

2022-02-16 16:15 UTC, justin-stephenson commented
> So the only thing that needs to get fixed is the changelog then. However, I do see F35 and F36 RPMs in the release directories. Does this mean there is a working RPM spec file already? If so, could you please update the one in the main branch? I wanted to complete this pull request. But if this is already done, then there is no need to spend time on it.

I've tried to keep an accurate changelog but if I missed something just let me know and I'll fix it: https://src.fedoraproject.org/rpms/tlog/blob/rawhide/f/tlog.spec

2022-02-16 21:42 UTC, kees-closed commented
When I try to build the spec file from Fedora src, I get:
```
RPM build errors:
    bogus date in %changelog: Tue Jan 19 2020 Justin Stephenson <jstephen@redhat.com> - 11-1
    Bad exit status from /var/tmp/rpm-tmp.3tqnuD (%build)
```

I solved these in the spec file. I did a pull request in the Fedora src repo before, but I was told I should do the pull request here. Either is fine for me. Then I'll just update the changelog so that the RPM builds again and perhaps we can open a branch for EPEL8. It's probably best to keep the spec file up to date in Fedora src, since rebuilds also create changelog entries. That may also be the problem of why the changelog got into the wrong order.

2022-02-24 16:01 UTC, justin-stephenson commented
> When I try to build the spec file from Fedora src, I get:
> 
> ```
> RPM build errors:
>     bogus date in %changelog: Tue Jan 19 2020 Justin Stephenson <jstephen@redhat.com> - 11-1
>     Bad exit status from /var/tmp/rpm-tmp.3tqnuD (%build)
> ```
> 
> I solved these in the spec file. I did a pull request in the Fedora src repo before, but I was told I should do the pull request here. Either is fine for me. Then I'll just update the changelog so that the RPM builds again and perhaps we can open a branch for EPEL8. It's probably best to keep the spec file up to date in Fedora src, since rebuilds also create changelog entries. That may also be the problem of why the changelog got into the wrong order.

I fixed the invalidate date here: https://src.fedoraproject.org/rpms/tlog/c/07aece99c9ef9bcbc763204ddeef3106d91b7d8e

2022-02-25 13:15 UTC, kees-closed commented
Thanks for the fix, but it's actually more than that. The order is wrong of the changelog. I don't know how that happened, probably because Fedora updates the changelogs with mass rebuilds and such. So if you keep one spec file here and on Fedora src, then they can diverge. I would really just go for a spec file in Fedora src, and then just for Fedora. And then create other spec files for other distro's such as Debian/Ubuntu.

The error I still get:
```
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.ThdhG9 (%prep)
    bogus date in %changelog: Tue Jan 8 2020 Justin Stephenson <jstephen@redhat.com> - 10-1
    %changelog not in descending chronological order
    Bad exit status from /var/tmp/rpm-tmp.ThdhG9 (%prep)
```

2022-02-25 13:23 UTC, Conan-Kudo commented
Another option is to simply have an empty changelog section upstream, so that merging in updates to downstream Fedora isn't problematic.

2022-02-28 13:53 UTC, justin-stephenson commented
> Thanks for the fix, but there are more issues. The changelog order is incorrect. I don't know how that happened, probably because Fedora updates the changelogs with mass rebuilds and such. So if you keep one spec file here and on Fedora src, then they can diverge. I would really just go for a spec file in Fedora src, and then just for Fedora. And then create other spec files for other distro's such as Debian/Ubuntu. The changelog is fixed in the pull request, but I don't think this is the place to keep the spec file.
> 
> The error I still get:
> 
> ```
> RPM build errors:
> error: Bad exit status from /var/tmp/rpm-tmp.ThdhG9 (%prep)
>     bogus date in %changelog: Tue Jan 8 2020 Justin Stephenson <jstephen@redhat.com> - 10-1
>     %changelog not in descending chronological order
>     Bad exit status from /var/tmp/rpm-tmp.ThdhG9 (%prep)
> ```

Which spec file are you using which generates this error?

2022-02-28 13:54 UTC, justin-stephenson commented
> Another option is to simply have an empty changelog section upstream, so that merging in updates to downstream Fedora isn't problematic. That's what the DNF team and others do.

Could you link to an example of this? It sounds like a simple approach we could use.

2022-03-01 07:26 UTC, kees-closed commented
> Which spec file are you using which generates this error?

I do the following:
* `dnf download --source tlog`
* `rpmdev-extract tlog-11-4.fc35.src.rpm`
* Download the tlog.tar.gz and place it in the proper SOURCE dir in your rpmbuild tree
* `rpmbuild -bs tlog.spec`
* And then `mock` build the srpm, which will bump with that error

But I guess you haven't updated this in the repo yet, so I'm testing the wrong spec file. If it works for you, then please update tlog and I would also highly appreciate it if you make tlog available for EPEL.

2022-03-01 17:42 UTC, justin-stephenson commented
> 

Can you please try with https://src.fedoraproject.org/rpms/tlog/blob/rawhide/f/tlog.spec and let me know if it works for you or not?

2022-03-02 18:41 UTC, justin-stephenson commented
> > Can you please try with https://src.fedoraproject.org/rpms/tlog/blob/rawhide/f/tlog.spec and let me know if it works for you or not?
> 
> Doesn't seem to build in `mock`, does it work for you? Because that would be odd.
> 
> ```
> Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.y7M3HS
> + umask 022
> + cd /builddir/build/BUILD
> + cd tlog-12
> + CFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'
> + export CFLAGS
> + CXXFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'
> + export CXXFLAGS
> + FFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules'
> + export FFLAGS
> + FCFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules'
> + export FCFLAGS
> + LDFLAGS='-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 '
> + export LDFLAGS
> + LT_SYS_LIBRARY_PATH=/usr/lib64:
> + export LT_SYS_LIBRARY_PATH
> + CC=gcc
> + export CC
> + CXX=g++
> + export CXX
> + '[' '-flto=auto -ffat-lto-objectsx' '!=' x ']'
> ++ find . -type f -name configure -print
> + '[' 1 = 1 ']'
> +++ dirname ./configure
> ++ find . -name config.guess -o -name config.sub
> + '[' 1 = 1 ']'
> + '[' x '!=' 'x-Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld' ']'
> ++ find . -name ltmain.sh
> + ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-rpath --disable-static --enable-utempter --docdir=/usr/share/doc/tlog
> /var/tmp/rpm-tmp.y7M3HS: line 62: ./configure: No such file or directory
> error: Bad exit status from /var/tmp/rpm-tmp.y7M3HS (%build)
> ```

Thanks, I see the issue now - the year was not bumped properly.

https://src.fedoraproject.org/rpms/tlog/c/e14fdfed04e733a084b66a75c4c9b464eb5143d7?branch=rawhide

Note that `dnf download --source` is not retrieving the latest version.

2022-03-03 11:10 UTC, kees-closed commented
Same issue still occurs, I indeed use the rawhide spec file you link to as well. Does it build for you in `mock`?

```
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.qAChRm
+ umask 022
+ cd /builddir/build/BUILD
+ cd tlog-12
+ CFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'
+ export CFLAGS
+ CXXFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'
+ export CXXFLAGS
+ FFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules'
+ export FFLAGS
+ FCFLAGS='-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/usr/lib64/gfortran/modules'
+ export FCFLAGS
+ LDFLAGS='-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 '
+ export LDFLAGS
+ LT_SYS_LIBRARY_PATH=/usr/lib64:
+ export LT_SYS_LIBRARY_PATH
+ CC=gcc
+ export CC
+ CXX=g++
+ export CXX
+ '[' '-flto=auto -ffat-lto-objectsx' '!=' x ']'
++ find . -type f -name configure -print
+ '[' 1 = 1 ']'
+++ dirname ./configure
++ find . -name config.guess -o -name config.sub
+ '[' 1 = 1 ']'
+ '[' x '!=' 'x-Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld' ']'
++ find . -name ltmain.sh
+ ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-rpath --disable-static --enable-utempter --docdir=/usr/share/doc/tlog
/var/tmp/rpm-tmp.qAChRm: line 62: ./configure: No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.qAChRm (%build)
```

2022-03-03 20:56 UTC, justin-stephenson commented
Hi,

It is successful when I run `fedpkg mockbuild` from the fedora rawhide source repository.

~~~
[justin@agalloch tlog]$ fedpkg mockbuild
...
<snip>
...
Wrote: /builddir/build/RPMS/tlog-12-2.fc37.x86_64.rpm
Wrote: /builddir/build/RPMS/tlog-debuginfo-12-2.fc37.x86_64.rpm
Wrote: /builddir/build/RPMS/tlog-debugsource-12-2.fc37.x86_64.rpm
Executing(%clean): /bin/sh -e /var/tmp/rpm-tmp.X1NaLk
+ umask 022
+ cd /builddir/build/BUILD
+ cd tlog-12
+ /usr/bin/rm -rf /builddir/build/BUILDROOT/tlog-12-2.fc37.x86_64
+ RPM_EC=0
++ jobs -p
+ exit 0
Finish: rpmbuild tlog-12-2.fc37.src.rpm
Finish: build phase for tlog-12-2.fc37.src.rpm
INFO: Done(/home/justin/fedpkg/tlog/tlog-12-2.fc37.src.rpm) Config(fedora-rawhide-x86_64) 0 minutes 56 seconds
INFO: Results and/or logs in: /home/justin/fedpkg/tlog/results_tlog/12/2.fc37
INFO: Cleaning up build root ('cleanup_on_success=True')
Start: clean chroot
Finish: clean chroot
Finish: run
~~~

It looks like your error is different than before, cannot find `./configure` - i.e. not changelog related this time?
~~~
+ ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-rpath --disable-static --enable-utempter --docdir=/usr/share/doc/tlog
/var/tmp/rpm-tmp.qAChRm: line 62: ./configure: No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.qAChRm (%build)
~~~

2022-03-04 08:25 UTC, kees-closed commented
That is correct, but I also mentioned this [here](https://github.com/Scribery/tlog/pull/337#issuecomment-1056676690). If the build works, could you then please create a branch for EPEL8? Thanks!

2022-04-01 12:11 UTC, kees-closed commented
Hi @justin-stephenson, could you please create an EPEL8/9 branch for [tlog](https://src.fedoraproject.org/rpms/tlog)?

2022-04-01 14:47 UTC, justin-stephenson commented
> Hi @justin-stephenson, could you please create an EPEL8/9 branch for [tlog](https://src.fedoraproject.org/rpms/tlog)?

Yes I will work on it, sorry for the delay.

2022-04-21 11:12 UTC, kees-closed commented
Hi @justin-stephenson, I don't see a branch yet [here](https://src.fedoraproject.org/rpms/tlog), do you need any assistance to make this happen?

2022-04-21 19:22 UTC, justin-stephenson commented
> Hi @justin-stephenson, I don't see a branch yet [here](https://src.fedoraproject.org/rpms/tlog), do you need any assistance to make this happen?

Sorry for the delay, i'll work on it soon.

2022-04-22 16:20 UTC, justin-stephenson commented
@kees-closed Can you please describe your use case/justification for requesting this package to be added into EPEL8/9, as tlog is already provided for RHEL8 and RHEL9 distributions.

2022-04-22 16:21 UTC, Conan-Kudo commented
> @kees-closed Can you please describe your use case/justification for requesting this package to be added into EPEL8/9, as tlog is already provided for RHEL8 and RHEL9 distributions.

It cannot be added to EPEL while it exists in RHEL.

2022-04-22 16:22 UTC, justin-stephenson commented
and just to clarify, the tlog package was published to EPEL7 because it is not available in RHEL7.

2022-04-25 08:37 UTC, kees-closed commented
> > @kees-closed Can you please describe your use case/justification for requesting this package to be added into EPEL8/9, as tlog is already provided for RHEL8 and RHEL9 distributions.
> 
> It cannot be added to EPEL while it exists in RHEL.

Even if that version is behind? Okay, then I guess it's fine like this.

2022-04-25 08:38 UTC, closed without merging